baseURL = 'https://nightfall-r.netlify.app/'
languageCode = 'en-us'
title = 'NightFall by RazioreG'
theme = 'nightfall'

[params]
user = "root"
hostname = "nightfall-r.netlify.app"
sitedescription = "Hugo Site Themed by NightFall by RazioreG"
published = true
readingTime = true

[params.author]
name = "RazioreG"
email = "enzoraziore@gmail.com"

[[params.social]]
key = "0"
name = "github"
url = "https://github.com/RazioreG"
target = "_blank"
aria = "Github Profile"

[[params.social]]
key = "1"
name = "twitter"
url = "https://twitter.com/RazioreG"
target = "_blank"
aria = "Twitter Profile"

[[params.social]]
key = "2"
name = "email"
url = "mailto:enzoraziore@gmail.com"

[menu]
[[menu.header]]
name = "about"
weight = 0
url = "about"

[[menu.header]]
name = "posts"
weight = 0
url = "blog"

[[menu.header]]
name = " "
weight = 1
url = "/"